### ISSUE TITLE
Asset downloads failed

### ISSUE THREAD

**Issue by EternalDeiwos** [nathan-sain/foundry-world-tools#11]
I attempted to download world assets locally using:

```shell
fwt download --type actors --asset-dir actors .
```

Which produced the following error:

```
Error: --type only allows 'actors' or 'items'
```

**Comment by nathan-sain** [comment]
Thanks for reporting this. There was a logical error in parsing the command line options for the download command. I've pushed a fix to the repo. You should be able to update and run the download for actors now.
